### PR TITLE
Create docs for in-memory testing utilizing FM

### PR DESCRIPTION
**Pull request by schambers**
I believe this is the correct manner of adding new docs. Unsure if there's any steps needed for generating docs.

### CODE REVIEW

**Comment by schambers** [comment]
@jzabroski or @eloekset, Are you good with me merging this? I noticed the build failed but it seemed unrelated and I don't believe I have access to ADO to attempt to restart the build

**Comment by jzabroski** [comment]
It looks like the documentation is failing to build for some reason. Let's first look into that before merging, but the plan is that this is 'functionally approved to be merged'. I think it's awesome.

**Comment by schambers** [comment]
Are you able to grant me access to retry the build by chance?

**Comment by jzabroski** [comment]
I queued it up. Commuting. Maybe around 9pm est

**Comment by jzabroski** [comment]
I believe I fixed the issue. I believe Ubuntu-latest no longer installed dotnet by default

**Comment by jzabroski** [comment]
@eloekset im not sure why it's not using the latest pipelines yaml? Is there a trick to getting a failed PR check to use the latest yaml pipeline? I swear I thought that this would just work. 

In any case, I plan to remove the change I made to the yaml as I realized it was incorrect and the real fix was to update global.json - I'll also add a comment before that step that if the sdk is not found, to check global.json

**Comment by jzabroski** [comment]
@eloekset Think I figured it out.  I made the master branch protected here and it gave me the option to rebase this PR to the head of master.

**Pull request merged**
