### PR TITLE
Updated Tag Documentation Article

### PR DESCRIPTION
**Pull request by zendever**
This goes along with the recent issue fluentmigrator/fluentmigrator#1026 and commit fluentmigrator/fluentmigrator#1027

### CODE REVIEW

**Comment by fubar-coder** [comment]
LGTM 👍

**Comment by jzabroski** [comment]
I think some of the grammar could be better (the use of "scenarios" and "contexts" here reads a bit jarring to me, not sure why), but let's merge it and improve it later. Not to pound the philosophical pavement, but, thinking back to me Use Cases software engineering class in college:

> A Scenario involves a situation that may have single or multiple actors that take a given functionality or path to resolve the scenario. You can see the main difference is "perspective" here. Usually, the use case is more granular than the scenario.

I would maybe put some of the regulatory color you shared in here as well - perhaps there is a visible business reason to have multiple separate databases but a single code base, especially for data seeding scripts.

**Comment by zendever** [comment]
@jzabroski - I don't disagree that there is room for improvement on the documentation. This was more of a contribution for discussion, primarily because I thought having something was better than nothing.

So, the first example added definitely was more use case than scenario. The use case for single-inheritance of tags will always be for simplicity or conciseness...unless you can think of another real reason. I think we can just drop the word scenario there, and change it to +use case+.

The second example really is a scenario, in my opinion given that the scenario IS having sharding by regulatory or geographical jurisdictions AND each database shares multiple combinations of contextual application (i.e. context by feature and/or implementation). While it may make some sense, in some cases to have separate migrations for each context, sometimes features aren't fully segregated. This will be more true with application suites where there may be cross functional dependencies (stuff that's shared) between disparate implemented features (stuff that's not shared)...a good example may be a feature that shares a security/privilege framework (e.g. uses common migrations for a Security Context) but has feature specific requirements for integrating and enforcing the Security Context within the Feature's Context. Rather than deploying unused framework schema for unused features in all installations, contextualizing the installation and applying only relevant features and dependencies makes more sense.

I'm confident it's a matter of grammar and idiomatic differences between you and me...however, I believe I'll be fine with whatever changes you propose as I believe the essence of our truths are shared.

**Comment by jzabroski** [comment]
I get it.  I'm just sharing some perspective.  We can try to improve the
wording next week - I am heads down on client work this week.  For now, I
am VERY thankful for your contributions, not only in source code, but
willingness to jump in and help document.  THANK YOU!

**Pull request merged**
